language: cpp
script: make
before_install:
- openssl aes-256-cbc -K $encrypted_5a3453517de6_key -iv $encrypted_5a3453517de6_iv -in cplusplus_rsa.enc -out deploy_rsa -d
before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ $SSHUSER@$DEPLOYHOST:$DEPLOYPATH
  on:
  branch: master
  